run:
  name: baseline
  storage: gs://rainfinder-mljec-200625/results

data:
  location: gs://rainfinder-mljec-200625/data
  split: [100, 2, -1]
  batch_size: 128

model:
  type: plain
  num_layers: 10
  num_units: 512

loss: mae

train:
  steps_per_epoch: 1000
  learning_rate: 5.e-4
  reduce_lr_on_plateau:
    factor: 0.2
    patience: 10
    min_delta: &min_delta 5.e-5
  early_stopping:
    patience: 15
    min_delta: *min_delta

predict: true
